spring:
  application:
    name: spring-boot-essentials

  datasource:
    url: jdbc:postgresql://localhost:5432/cadastro_clientes
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true